---
title: "Clustering trajectories"
author: "Juan R Gonzalez"
output:
  BiocStyle::pdf_document:
    fig_caption: yes
    toc_depth: 2
  BiocStyle::html_document:
    toc_depth: 2
---

<!-- to compile this:
library("rmarkdown");
render("rr-auhtoring.Rmd", output_format="all")
or just call make
-->

```{r style, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
library("knitr")
#options(width=100)
opts_chunk$set(message = FALSE, error = TRUE, warning = FALSE)
```


# Introduction

> **Objectives**
>
> * Learn how to find a model or method to address an specific scientific question where the model is not know by the student.
> * Peform data analyses where the scientific question is to determine cluster of individuals having the same trajectory of longitudinal data.

# The problem

The data set called `hiv_data.txt`, which is available at Moodle, contains information about individuals (variable `id`) whose CD4 levels (variable `CD4`), which is an indicator of the HIV viral load, have been measured over time (variable `month`). The individuals have been treated with one or two drugs (variable `group`) having another group of patients who have not been treated (control group). 

The aim of the researchers is to demonstrate which is the best therapeutic option. The tasks you should perform are:

> *Answer this question using any of the models you have learnt during the course

> *Suppose that the researchers want to classify individuals having similar trajectories over time and then assess whether these trajectories (e.g. categorical variable) is associated with the different treatments. You should carry out next tasks in order to address this question:

- Find a method (in R) to perform clustering or trajectories (NOTE: there are several, you should do what you think it is important to address this specific question. I mean, select one or compare the results obtained when using different ones). Briefly describe the method you are using

- Perform the analysis using the strategy you think is more appropiated (I mean, maybe the approach proposed in the question is not the best one - HINT: consider analyzing everything in a single model and compare both results)

- Create a reproducible report having `echo=TRUE` in the chunks. Include some figures and comment the main results you have obained from the analyses. Upload the pdf file in the Campus Virtual. There is not page limit, but the report shouldn't be too long. Let us imagine you are preparing a document to be read by biologists or medical doctors. 


